
package org.shaddy.web.services.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShaddyStoreServices", targetNamespace = "http://services.web.shaddy.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShaddyStoreServices {


    /**
     * 
     * @param prodCode
     * @return
     *     returns org.shaddy.web.services.client.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByProductCode", targetNamespace = "http://services.web.shaddy.org/", className = "org.shaddy.web.services.client.FindByProductCode")
    @ResponseWrapper(localName = "findByProductCodeResponse", targetNamespace = "http://services.web.shaddy.org/", className = "org.shaddy.web.services.client.FindByProductCodeResponse")
    @Action(input = "http://services.web.shaddy.org/ShaddyStoreServices/findByProductCodeRequest", output = "http://services.web.shaddy.org/ShaddyStoreServices/findByProductCodeResponse")
    public Product findByProductCode(
        @WebParam(name = "prodCode", targetNamespace = "")
        String prodCode);

    /**
     * 
     * @return
     *     returns java.util.List<org.shaddy.web.services.client.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveListOfProducts", targetNamespace = "http://services.web.shaddy.org/", className = "org.shaddy.web.services.client.RetrieveListOfProducts")
    @ResponseWrapper(localName = "retrieveListOfProductsResponse", targetNamespace = "http://services.web.shaddy.org/", className = "org.shaddy.web.services.client.RetrieveListOfProductsResponse")
    @Action(input = "http://services.web.shaddy.org/ShaddyStoreServices/retrieveListOfProductsRequest", output = "http://services.web.shaddy.org/ShaddyStoreServices/retrieveListOfProductsResponse")
    public List<Product> retrieveListOfProducts();

}
