
package org.shaddy.web.services.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShaddyStoreServices", targetNamespace = "http://services.web.shaddy.org/", wsdlLocation = "http://localhost:8080/ShaddyStore-war/ShaddyStoreServices?wsdl")
public class ShaddyStoreServices_Service
    extends Service
{

    private final static URL SHADDYSTORESERVICES_WSDL_LOCATION;
    private final static WebServiceException SHADDYSTORESERVICES_EXCEPTION;
    private final static QName SHADDYSTORESERVICES_QNAME = new QName("http://services.web.shaddy.org/", "ShaddyStoreServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ShaddyStore-war/ShaddyStoreServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHADDYSTORESERVICES_WSDL_LOCATION = url;
        SHADDYSTORESERVICES_EXCEPTION = e;
    }

    public ShaddyStoreServices_Service() {
        super(__getWsdlLocation(), SHADDYSTORESERVICES_QNAME);
    }

    public ShaddyStoreServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHADDYSTORESERVICES_QNAME, features);
    }

    public ShaddyStoreServices_Service(URL wsdlLocation) {
        super(wsdlLocation, SHADDYSTORESERVICES_QNAME);
    }

    public ShaddyStoreServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHADDYSTORESERVICES_QNAME, features);
    }

    public ShaddyStoreServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShaddyStoreServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShaddyStoreServices
     */
    @WebEndpoint(name = "ShaddyStoreServicesPort")
    public ShaddyStoreServices getShaddyStoreServicesPort() {
        return super.getPort(new QName("http://services.web.shaddy.org/", "ShaddyStoreServicesPort"), ShaddyStoreServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShaddyStoreServices
     */
    @WebEndpoint(name = "ShaddyStoreServicesPort")
    public ShaddyStoreServices getShaddyStoreServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.web.shaddy.org/", "ShaddyStoreServicesPort"), ShaddyStoreServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHADDYSTORESERVICES_EXCEPTION!= null) {
            throw SHADDYSTORESERVICES_EXCEPTION;
        }
        return SHADDYSTORESERVICES_WSDL_LOCATION;
    }

}
